title: <p align="center"> Sai Sharan </p>
logo: /assets/img/WhatsApp Image 2022-04-11 at 6.29.36 PM.jpeg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/sai-sharan-paspunuri/">LinkedIn</a> |
  <a href="https://drive.google.com/file/d/1uA-U25AaZ-RBpLsygIU6zrmbt6PIktqy/view?usp=sharing">Resume</a> |
  <a href="https://github.com/sai-sharan-p">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in AdTech domain for 3 years.
  <br>   
  </p>



theme: jekyll-theme-minimal
