title: <p align="center"> Sai Sharan </p>
logo: /assets/img/WhatsApp Image 2022-04-11 at 6.29.36 PM.jpeg
description:              
<p align="center"> </p>
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
show_downloads: true

theme: jekyll-theme-minimal
